using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpawnManager : MonoBehaviour
{
    // Start is called before the first frame update

    public GameObject BasicMonster;
    public GameObject BossMonster;

    public Transform SpawnArea; // Spawn that basic monster instantiate

    public Transform Player;

    public float spawnHeight; // spawn height

    public float minRadius; //Spawn minimum of random values
    public float maxRadius; //attack maximum of random values

    public int NumofBasicMonster = 5; // num of Basic Monster

    public GameObject warningMessage; // warning massage prefbas

    private bool Stop = false; // boss monster should be spawn once!!!

    private int CycleMon;

    Fire fire;
    Water water;
    Electricity electricity;

    private void Awake()
    {
        fire = FindObjectOfType<Fire>();
        water = FindObjectOfType<Water>();
        electricity = FindAnyObjectByType<Electricity>();
    }
    void Start()
    {
        Stop = true; // control Boss spawn
        CycleMon = NumofBasicMonster; // to control basic monster
        spawnHeight = 2f; // spawn height
        Player = GameObject.FindGameObjectWithTag("Player").transform;
        //transform.position = Player.position;
        StartCoroutine("SpawnBasic");
    }

    // Update is called once per frame
    void Update()
    {
        if(this.gameObject.transform.childCount < 1 && NumofBasicMonster < 1 && Stop ) //When there are no children and the number of basic monsters becomes 0
        {
            warningMessage.SetActive(true); // show warning message
            if(fire.fireCheck == true && water.waterCheck == true && electricity.electricCheck == true)// if you get all of skills boss will be spawn
            {
                warningMessage.SetActive(false);// show warning message
                SpawnBoss(); // spawn Boss monster
                Stop = false; // stop spawn Boss monster
            }
        }
    }


    private Vector3 GetRandomPositionOnCircle(float radius) // A function that generates ice at random coordinates within a circle radius
    {
        Vector3 randomDirection = Random.onUnitSphere; // random value in circle radius
        randomDirection.y = 0; //Create a circular shape by fixing the y-axis to 0

        float r = Random.Range(minRadius, radius);
        /*This code generates a random float value between 0.0f and radius.

          Here, Random is a class that generates random values ​​provided by Unity, and Range() is a method that returns values ​​generated by this Random class within a specified range.

        So, we assign the r variable a random value generated between 0.0f and radius.*/ 
        return (randomDirection * r) + SpawnArea.position; // Implemented a function to move a game object from its current location to a random location within a certain range
        /*
        float randomAngle = Random.Range(-(Mathf.PI)/2, (Mathf.PI)/2); // 무작위 각도 선택
        Vector3 randomDirection = new Vector3(Mathf.Sin(randomAngle), 0, Mathf.Cos(randomAngle)); // 무작위 방향 벡터 생성
        float r = Random.Range(minRadius, radius); // 반지름 내에서 무작위 반지름 선택
        Vector3 randomPosition = (randomDirection * r) + Player.position; // 위치 계산
        return randomPosition;
        */
    }


    IEnumerator SpawnBasic()
    {
        for(int i = 0; i < CycleMon; i++) // you can change numofbasicMonster
        {
            Vector3 spawnPosition = GetRandomPositionOnCircle(maxRadius); // call func that return instantiate position
            spawnPosition.y = spawnHeight; // set height
            GameObject go = Instantiate(BasicMonster, spawnPosition, Quaternion.identity);
            go.transform.parent = this.transform; // put it as a child of Basic Monster
            //SpawnIceObject[randomValue].transform.parent = this.transform;
            yield return new WaitForSeconds(3.0f);
        }
        StopCoroutine("SpawnBasic"); // if cycleMon is done stop Spawn BasicMonster
    }

     void SpawnBoss() // func that spawn Boss
    {
        GameObject go = Instantiate(BossMonster, new Vector3(Player.position.x,Player.position.y,Player.position.z + 2.0f), Quaternion.identity);
        go.transform.parent = this.transform;
    }
}
